### ISSUE TITLE
Is it possible to define custom loss function ?

### ISSUE THREAD

**Issue by alexschickele** [supsi-dacd-isaac/mbtr#2]
Dear all,
First thank you for developping this tool, that I believe is of great interest. I am working with:
- environmental variables (e.g. temperature, salinity)
- multi-dimensional targets, that are relative abundance, with their sum = 1 for each site

Therefore, I was wondering if it is possible to implement a custom loss function in the mbtr framework, that would be adapted for proportions. Please note that I am quite new to python.

To do some testing, I tryed to dupplicate the `mse` loss function with another name in the `losses.py` file and adding the new loss in the `LOSS_MAP` in `__inits__.py`. Then I compiled the files.
However, I have this error when trying to run the model from the multi_reg.py example:

```
>>> m = MBT(loss_type = 'mse', n_boosts=30,  min_leaf=100, lambda_weights=1e-3).fit(x_tr, y_tr, do_plot=True)
  3%|▎         | 1/30 [00:03<01:45,  3.63s/it]
>>> m = MBT(loss_type = 'custom_mse', n_boosts=30,  min_leaf=100, lambda_weights=1e-3).fit(x_tr, y_tr, do_plot=True)
  0%|          | 0/30 [00:00<?, ?it/s]KeyError: 'custom_mse'
```

It seems that the new loss is not recognised in LOSS_MAP:

```
>>> LOSS_MAP = {'custom_mse': losses.custom_MSE,
...             'mse': losses.MSE,
...             'time_smoother': losses.TimeSmoother,
...             'latent_variable': losses.LatentVariable,
...             'linear_regression': losses.LinRegLoss,
...             'fourier': losses.FourierLoss,
...             'quantile': losses.QuantileLoss,
...             'quadratic_quantile': losses.QuadraticQuantileLoss}
AttributeError: module 'mbtr.losses' has no attribute 'custom_MSE'
```

I guess that I missed something when trying to dupplicate and rename the `mse` loss. I would appreciate any help if the definition of a custom loss function is possible.

Best regards,

**Comment by nepslor** [comment]
Dear @alexschickele this works on my PC. I did the following MVP:

1. recloned the repo
2. added the following MVP loss to `losses.py` : 
`class MSE_custom(MSE):
    def __init__(self, lambda_weights: float = 0.1, lambda_leaves: float = 0.1, **loss_kwargs):
        super().__init__(lambda_weights, lambda_leaves, **loss_kwargs)
`
3. added it into the `LOSS_MAP` of the` __init__.py`, as `'mse_custom':losses.MSE_custom`
4. tested running `multivariate_forecast.py` replacing line 60 to explicitly call the new loss 
`m = MBT(loss_type='mse_custom',n_boosts=30,  min_leaf=100, lambda_weights=1e-3).fit(x_tr, y_tr, do_plot=True)`

and it works. Is it possible that you didn't reload the console? Are you using pycharm as IDE?

**Comment by alexschickele** [comment]
Dear @nepslor 
Thank you for your help, it works very well ! 
Defining the custom loss function should not be a problem from now on.
As I am new to python, I may have missed something in while reloading the console or compiling the modified functio (I was on a Linux server with python open via Rstudio).



Best regards,
